### ISSUE TITLE
Regression: Redocusaurus can no longer load OpenAPI/Swagger 2.0 definitions

### ISSUE THREAD

**Issue by markcarroll** [rohit-gohri/redocusaurus#106]
Version 0.4.6 successfully loads and displays OpenAPI/Swagger v2.0 documents, but upgrading to v0.5 now returns an error:

```
    Error: Document must be valid OpenAPI 3.0.0 definition
```

Reverted to 0.4.6 and it works again.

**Comment by rohit-gohri** [comment]
Might be related to https://github.com/Redocly/redoc/issues/1724

Does your spec define a top level field `swagger: "2.0"`?

**Comment by markcarroll** [comment]
Yes it does.  

Mark

On Nov 30, 2021, at 8:11 PM, Rohit Gohri ***@***.***> wrote:

﻿
Might be related to Redocly/redoc#1724

Does your spec define a top level field swagger: "2.0"?

**Comment by joshuaflanagan** [comment]
> Might be related to [Redocly/redoc#1724](https://github.com/Redocly/redoc/issues/1724)

It is not - in that issue, the reporter had an invalid spec (version specified as an integer instead of a string).

I tested and verified that redoc-cli can properly load Swagger 2.0 files. However, it does report that it converts the file to 3.0 first:

```
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
```

which I've tracked down to the [loadAndBundleSpec](https://github.com/Redocly/redoc/blob/4fb5f914fa4fe05ee8b24cc15cb485f7b3538538/src/utils/loadAndBundleSpec.ts#L40) utility function in redoc.

It seems like redocusaurus might be initiating redoc in a way that bypasses that conversion.

**Comment by rohit-gohri** [comment]
@joshuaflanagan  Thanks for tracking it down! It seems they are using this function in StoreBuilder : https://github.com/Redocly/redoc/blob/6c7685e5fa04314328a445d7077600692c49489c/src/components/StoreBuilder.ts

If we switch to using StoreBuilder too for creating the AppStore here: https://github.com/rohit-gohri/redocusaurus/blob/4875be7ac987ec45664dc91d6f9ff99e6beb81ff/packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx#L21-L28

Then this will solve both this and #80 I think.

**Comment by rohit-gohri** [comment]
I have released a beta for v1 where this is fixed: https://github.com/rohit-gohri/redocusaurus/discussions/146

It has some breaking changes (mostly simplification of option names). New docs are at https://redocusaurus-v1.vercel.app/docs 

It will be great if you could try it and give some feedback.

**Comment by joshuaflanagan** [comment]
I am trying to test it, but am running into errors. However, it is difficult to tell the source, since I am also attempting to update my version of docusaurus at the same time. If you tell me the exact version of docusaurus that you are testing on and expect to support, I can use the same. They have been releasing a lot of betas recently which can add to the confusion.

**Comment by joshuaflanagan** [comment]
To be clear, in my package.json I have:

```  
  "@docusaurus/core": "^2.0.0-beta.17",
  "redocusaurus": "0.0.0-beta-20220314034003",
```

My attempt at running `docusaurus build` results in:

```
[INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: "layout" is not allowed
```

This appears to be referring to the spec definition in the redocusaurus config of `docusaurus.config.js`.

My `specs` config looks like:

```
  [{
    routePath: 'myservice/api',
    spec: 'myservice/api.yaml',
    layout: { title: 'Service API' }
  }]
```

When I delete the `layout` config line, I now get:

```
[INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: "debug" is not allowed
```

I don't specify `debug` anywhere. I also noticed that if I change `routePath` to `route` (which the [docs suggest](https://redocusaurus-v1.vercel.app/docs/getting-started/plugin-options)) I get `[ERROR] ValidationError: "route" is not allowed`.

**Comment by rohit-gohri** [comment]
Thanks for testing it out. Regarding beta, `beta.17` is what is supported and what I'm using too. 

And you are on the correct version of redocusaurus but my build was wrong. I just released a new version (from the latest commit) : `1.0.0-beta-20220315035651`. 

Verified the [dist files on unpkg](https://unpkg.com/browse/docusaurus-plugin-redoc@1.0.0-beta-20220315035651/dist/options.js) and tested it on a fresh project. It should be working now

**Comment by joshuaflanagan** [comment]
Thanks - that fixed it, I was able to get a successful build! I'll do more thorough testing tomorrow.

**Comment by joshuaflanagan** [comment]
This build is working for me and resolves this issue.

**Comment by rohit-gohri** [comment]
Awesome! Thanks for testing it out.

There are some minor styling changes compared to v0 (see [percy diff](https://percy.io/fef74697/redocusaurus/builds/16478400?utm_campaign=fef74697&utm_content=redocusaurus&utm_source=github_status_public)). I know the fix for most of those, so I'll release stable v1 once they are fixed.
