### ISSUE TITLE
Logo from spec (x-logo) not being rendered.

### ISSUE THREAD

**Issue by ksiczek** [rohit-gohri/redocusaurus#334]
Hi there, 

I configured a logo using the `x-logo` in the spec but it is getting rendered. I noticed that since the https://github.com/rohit-gohri/redocusaurus/issues/123, if the logo is defined in the spec, the very first item is hidden
```
.redocusaurus-has-logo .menu-content > div:first-child {
  display: none;
}
``` 
However, the thing is that the hidden item itself is the logo. Does the code say  _if there is a logo, hide the logo_? Or do I miss something?

**Comment by rohit-gohri** [comment]
Hi, that was intentional since docusaurus website headers usually have logos of it's own so to avoid double logos the api docs hides the logo. If it's needed I'll be happy to accept a PR that puts the feature behind an option

**Comment by ksiczek** [comment]
Does it mean the `x-logo` is redundant and using it is pointless? I'm docusaurus noob and I was just confused. Anyway, I'm ok with using the _general_ logo ☺️

**Comment by rohit-gohri** [comment]
> Does it mean the x-logo is redundant and using it is pointless? 

`x-logo` is a [redoc](https://github.com/Redocly/redoc/) feature, which is what we use to render the api docs, if you use just that directly then it is quite useful. 
But docusaurus provides site wide logo so we hide the logo in the api docs, otherwise it will be shown twice. 

> Anyway, I'm ok with using the general logo ☺️

Cool, I'll close this then. But feel free to open a discussion for questions or issue for bugs/features.
