### ISSUE TITLE
Improve behaviour with Algolia search

### ISSUE THREAD

**Issue by ArtFlag** [rohit-gohri/redocusaurus#66]
## Feature suggestion

I suppose that most users that need a search bar will use the Algolia plugin provided by docusaurus. 

Using this search, it can happen that you click on an API hit result, and it takes you to the right page, but not to the correct heading. Most probably because the page can take a bit too long to load, depending on your OAS file.

Here is an example. Notice that:
- the first search takes me to the top of the API docs, instead of the correct header.
- the second time I go to the search hit works fine, as the page is loaded.

![example](https://user-images.githubusercontent.com/25686502/124120731-632eb900-da74-11eb-9bb1-54aacb27c30f.gif)

I understand that the load times are purely redoc-related and there's nothing this great plugin can do about it. But maybe we could have some kind of property to manage a timer until the browser tries to reach the anchor. 
I'm not sure how to deal with this issue. 

Any ideas?

**Comment by rohit-gohri** [comment]
I think this would be solved by adding SSR support (#44)

**Comment by ArtFlag** [comment]
Great, you're already on it then 👍  Looking forward to see if that fixes this issue 🙂

**Comment by ArtFlag** [comment]
One other thing: 
On the video, you can see that the y scroll offset is incorrect once we get to the endpoint via the search. 

Would this be also fixed by #44 or is it a different problem?

**Comment by rohit-gohri** [comment]
offset could be a different problem. Can you share a link to your site/repo so I can recreate the issue?

**Comment by ArtFlag** [comment]
You can see it [here](https://docs.talon.one/), but the repo's private.

**Comment by rohit-gohri** [comment]
I think SSR should fix this, let me know if you try it out and problem still persists

**Comment by rohit-gohri** [comment]
Not sure how algolia indexes links (haven't used it), the recommended crawler config does seem to have index headings option which should pick up - https://docsearch.algolia.com/docs/templates/#docusaurus-v3-template

**Comment by jrub** [comment]
Yeah, the template seems good, but it won’t pick the pages generated by Redocusaurus. I checked all the listed websites in [Who is using Redocusaurus](https://redocusaurus.vercel.app/docs/who-is-using-redocusaurus) and none of them that include Algolia are indexing the OpenAPI sections correctly.

The problem seems to be that the HTML structure generated by Redocusaurus does not align well with Docusaurus’s default configuration for Algolia, it only indexes Docs and Blog posts. Also, the generated `sitemap.xml` only contains the root level of the API, as seen in your website examples ([sitemap](https://redocusaurus.vercel.app/sitemap.xml)). This means Algolia doesn’t get the complete list of URLs to index (or any other search crawler, for that matter).

I managed to get Algolia DocSearch working with Redocusaurus by using adequate selectors and adding it as a new action to the default template. Here’s the final configuration that worked for us:

```js
actions: [
  {
    indexName: "developers-quaderno",
    pathsToMatch: ["https://developers.quaderno.io/api/**"],
    recordExtractor: ({ $, helpers }) => {
      const lvl0 =
        $(
          ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active",
        )
          .last()
          .text() || "Quaderno API Documentation";

      return helpers.docsearch({
        recordProps: {
          lvl0: { selectors: "h1", defaultValue: lvl0 },
          lvl1: "div[id^='tag/'] h2",          // API tag (Transactions, Products, etc.)
          lvl2: "div[id^='operation/'] h2",     // Endpoint title (Create a transaction, etc.)
          content: ".property-name, div p, div li, pre code, table td",  // Parameters and JSON responses
        },
        aggregateContent: true,
        recordVersion: "v3",
      });
    },
  },
],
```

Hope this helps anyone facing similar issues!
