### ISSUE TITLE
How do I configure redoc typography?

### ISSUE THREAD

**Issue by fsargent** [rohit-gohri/redocusaurus#98]
Hiya, 

I've been chewing on this for a few days and can't find a good option, how do you pass theming options to Redoc?

IE: https://redoc.ly/docs/api-reference-docs/configuration/theming/

We'd like to change what the font is, and try to make the sidebar typography match Docusaurus' theme more, but I can't seem to get any of the attributes loaded when entering them through docusaurus.config.js.

Thanks!

**Comment by rohit-gohri** [comment]
That's because we currently override the theme options in the end with light/dark theme options here: https://github.com/rohit-gohri/redocusaurus/blob/main/packages/docusaurus-theme-redoc/src/redocTheme.ts

We could change the order, but if these improvements are not specific to your site's branding then I would encourage you to open a PR fixing the theme for everyone :D Will be happy to release a patch version.

**Comment by rohit-gohri** [comment]
v0.8.0 has a `redocTheme` option (https://github.com/rohit-gohri/redocusaurus/tree/main/packages/docusaurus-theme-redoc#redoctheme) to overwrite theme. You can configure typography through that, though I would still recommend anyone to open a PR and improve the style for everyone 🙂
